# Generated by Django 3.1.1 on 2020-10-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20201004_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='movie_name',
            field=models.TextField(unique=True),
        ),
    ]
