# Generated by Django 3.1.1 on 2020-10-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20201004_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearchhistory',
            name='movie_name',
            field=models.TextField(),
        ),
    ]
